// ML problem bank part A — NumPy (5) + Pandas (5). Python problems run under Pyodide.
// Each case: { args, expected, sample } — expected values generated by executing the
// reference solutions (floats pre-rounded to 6 decimals). Pushes into window.ML_PROBLEMS.
(function () {
  "use strict";
  var M = (window.ML_PROBLEMS = window.ML_PROBLEMS || []);
  var problems = [
{
  "slug": "np-normalize-columns",
  "name": "Normalize Every Column",
  "category": "NumPy",
  "difficulty": "Easy",
  "sub": "Broadcasting",
  "maxScore": 20,
  "successRate": "84.10%",
  "lang": "python",
  "fn": "normalize_columns",
  "statement": "\n<p><b>Why this matters:</b> ML models train badly when one feature is \"salary in dollars\" (huge numbers) and another is \"years of experience\" (small numbers). <em>Min-max normalization</em> rescales every column to the 0–1 range so features compete fairly. In the browser you'd write nested <code>for</code> loops — in NumPy you write one line, because operations <em>broadcast</em> across whole arrays at once.</p>\n<p>Write <code>normalize_columns(matrix)</code> that takes a 2D list of numbers and rescales <strong>each column independently</strong>: <code>(x - col_min) / (col_max - col_min)</code>. If a column is constant (max == min), map the whole column to <code>0.0</code> instead of dividing by zero.</p>\n<p>Return a plain 2D Python list with every value rounded to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>normalize_columns([[1, 10], [2, 20], [3, 30]])\n-&gt;  [[0.0, 0.0], [0.5, 0.5], [1.0, 1.0]]</pre>\n<h3>Goal</h3>\n<p>No Python loops over rows or columns. Use <code>arr.min(axis=0)</code>, <code>arr.max(axis=0)</code> and let broadcasting do the row-wise work. Handle the constant column with <code>np.where</code>.</p>",
  "starter": "import numpy as np\n\ndef normalize_columns(matrix):\n    # matrix: 2D list of numbers\n    # Return a 2D list, each column min-max scaled to [0, 1],\n    # constant columns become all 0.0, values rounded to 6 decimals.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import numpy as np\n\ndef normalize_columns(matrix):\n    arr = np.array(matrix, dtype=float)\n    col_min = arr.min(axis=0)          # shape (n_cols,) — one min per column\n    col_max = arr.max(axis=0)\n    rng = col_max - col_min\n    safe = np.where(rng == 0, 1, rng)  # avoid divide-by-zero; numerator is 0 there anyway\n    out = (arr - col_min) / safe       # broadcasting: (rows, cols) - (cols,)\n    out = np.where(rng == 0, 0.0, out) # constant columns -> 0.0\n    return np.round(out, 6).tolist()\n",
    "explanation": "<p>Broadcasting stretches the per-column <code>min</code>/<code>max</code> vectors across every row, so the whole rescale is three vectorized lines. The <code>np.where</code> pair is the standard trick for divide-by-zero-safe normalization: substitute a harmless denominator, then overwrite the affected columns.</p>"
  },
  "cases": [
    {
      "args": [
        [
          [
            1,
            10
          ],
          [
            2,
            20
          ],
          [
            3,
            30
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          0.0
        ],
        [
          0.5,
          0.5
        ],
        [
          1.0,
          1.0
        ]
      ],
      "sample": true
    },
    {
      "args": [
        [
          [
            0,
            5,
            100
          ],
          [
            10,
            5,
            200
          ],
          [
            5,
            5,
            150
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          0.0,
          0.0
        ],
        [
          1.0,
          0.0,
          1.0
        ],
        [
          0.5,
          0.0,
          0.5
        ]
      ],
      "sample": true
    },
    {
      "args": [
        [
          [
            42
          ]
        ]
      ],
      "expected": [
        [
          0.0
        ]
      ],
      "sample": false
    },
    {
      "args": [
        [
          [
            -2,
            4
          ],
          [
            2,
            -4
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          1.0
        ],
        [
          1.0,
          0.0
        ]
      ],
      "sample": false
    },
    {
      "args": [
        [
          [
            1.5,
            2.5
          ],
          [
            3.5,
            2.5
          ],
          [
            2.5,
            2.5
          ],
          [
            1.5,
            2.5
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          0.0
        ],
        [
          1.0,
          0.0
        ],
        [
          0.5,
          0.0
        ],
        [
          0.0,
          0.0
        ]
      ],
      "sample": false
    }
  ]
},
{
  "slug": "np-moving-average",
  "name": "Moving Average, No Loops",
  "category": "NumPy",
  "difficulty": "Medium",
  "sub": "Vectorization",
  "maxScore": 25,
  "successRate": "76.42%",
  "lang": "python",
  "fn": "moving_average",
  "statement": "\n<p><b>Why this matters:</b> a raw metric (daily active users, stock price, sensor noise) is jumpy. A <em>moving average</em> smooths it: each output point is the mean of the last <code>k</code> input points. You have done this in JS with a sliding-window loop — the NumPy way is a <em>cumulative sum</em> trick that computes every window in one shot.</p>\n<p>Write <code>moving_average(values, k)</code> returning the list of means of every length-<code>k</code> window, left to right. For <code>n</code> inputs you return <code>n - k + 1</code> outputs. You may assume <code>1 &lt;= k &lt;= n</code>.</p>\n<p>Return a plain list rounded to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>moving_average([1, 2, 3, 4, 5], 3)  -&gt;  [2.0, 3.0, 4.0]</pre>\n<h3>Goal</h3>\n<p>No Python <code>for</code> loop over windows. Hint: if <code>c = np.cumsum(values)</code> then the sum of window ending at <code>i</code> is <code>c[i] - c[i-k]</code>. Slicing two shifted copies of <code>c</code> and subtracting gives every window sum at once.</p>",
  "starter": "import numpy as np\n\ndef moving_average(values, k):\n    # values: list of numbers, k: window size (1 <= k <= len(values))\n    # Return list of window means, rounded to 6 decimals. No window loops.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import numpy as np\n\ndef moving_average(values, k):\n    arr = np.array(values, dtype=float)\n    c = np.cumsum(arr)\n    # window sums: c[k-1], c[k]-c[0], c[k+1]-c[1], ...\n    sums = c[k - 1:].copy()\n    sums[1:] -= c[:-k]\n    return np.round(sums / k, 6).tolist()\n",
    "explanation": "<p>The cumulative-sum identity <code>sum(a[i-k+1..i]) = c[i] - c[i-k]</code> turns an O(n·k) sliding window into two O(n) slices and a subtraction. This exact trick shows up everywhere in feature engineering for time-series models.</p>"
  },
  "cases": [
    {
      "args": [
        [
          1,
          2,
          3,
          4,
          5
        ],
        3
      ],
      "expected": [
        2.0,
        3.0,
        4.0
      ],
      "sample": true
    },
    {
      "args": [
        [
          10,
          20,
          30,
          40
        ],
        2
      ],
      "expected": [
        15.0,
        25.0,
        35.0
      ],
      "sample": true
    },
    {
      "args": [
        [
          5,
          5,
          5,
          5
        ],
        4
      ],
      "expected": [
        5.0
      ],
      "sample": false
    },
    {
      "args": [
        [
          3,
          -1,
          4,
          -1,
          5,
          -9,
          2,
          6
        ],
        3
      ],
      "expected": [
        2.0,
        0.666667,
        2.666667,
        -1.666667,
        -0.666667,
        -0.333333
      ],
      "sample": false
    },
    {
      "args": [
        [
          7
        ],
        1
      ],
      "expected": [
        7.0
      ],
      "sample": false
    },
    {
      "args": [
        [
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
          0.6
        ],
        5
      ],
      "expected": [
        0.3,
        0.4
      ],
      "sample": false
    }
  ]
},
{
  "slug": "np-one-hot",
  "name": "One-Hot Encoding",
  "category": "NumPy",
  "difficulty": "Easy",
  "sub": "Indexing",
  "maxScore": 20,
  "successRate": "88.03%",
  "lang": "python",
  "fn": "one_hot",
  "statement": "\n<p><b>Why this matters:</b> models do math, and you cannot multiply the category \"blue\". <em>One-hot encoding</em> turns class id <code>2</code> (out of 4 classes) into the vector <code>[0, 0, 1, 0]</code> — a 1 in the class's slot, 0 everywhere else. It is the standard way categorical labels enter a neural network, and the same idea as a <code>&lt;select&gt;</code> where exactly one option is chosen.</p>\n<p>Write <code>one_hot(labels, num_classes)</code> taking a list of integer class ids (each in <code>0..num_classes-1</code>) and returning a 2D list of ints of shape <code>(len(labels), num_classes)</code>.</p>\n<h3>Example</h3>\n<pre>one_hot([0, 2, 1], 3)  -&gt;  [[1, 0, 0], [0, 0, 1], [0, 1, 0]]</pre>\n<h3>Goal</h3>\n<p>No loops. Classic NumPy idiom: build <code>np.eye(num_classes, dtype=int)</code> (the identity matrix) and <em>fancy-index</em> its rows with your label array — row <code>i</code> of the identity matrix is exactly the one-hot vector for class <code>i</code>.</p>",
  "starter": "import numpy as np\n\ndef one_hot(labels, num_classes):\n    # labels: list of ints in 0..num_classes-1\n    # Return 2D list of ints, shape (len(labels), num_classes).\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import numpy as np\n\ndef one_hot(labels, num_classes):\n    eye = np.eye(num_classes, dtype=int)  # row i = one-hot vector for class i\n    return eye[np.array(labels, dtype=int)].tolist()  # fancy indexing picks rows\n",
    "explanation": "<p>Fancy indexing (<code>eye[labels]</code>) gathers one identity-matrix row per label in a single vectorized gather — the same pattern PyTorch's <code>F.one_hot</code> uses under the hood.</p>"
  },
  "cases": [
    {
      "args": [
        [
          0,
          2,
          1
        ],
        3
      ],
      "expected": [
        [
          1,
          0,
          0
        ],
        [
          0,
          0,
          1
        ],
        [
          0,
          1,
          0
        ]
      ],
      "sample": true
    },
    {
      "args": [
        [
          1,
          1,
          1
        ],
        2
      ],
      "expected": [
        [
          0,
          1
        ],
        [
          0,
          1
        ],
        [
          0,
          1
        ]
      ],
      "sample": true
    },
    {
      "args": [
        [
          3
        ],
        4
      ],
      "expected": [
        [
          0,
          0,
          0,
          1
        ]
      ],
      "sample": false
    },
    {
      "args": [
        [
          0,
          1,
          2,
          3,
          4
        ],
        5
      ],
      "expected": [
        [
          1,
          0,
          0,
          0,
          0
        ],
        [
          0,
          1,
          0,
          0,
          0
        ],
        [
          0,
          0,
          1,
          0,
          0
        ],
        [
          0,
          0,
          0,
          1,
          0
        ],
        [
          0,
          0,
          0,
          0,
          1
        ]
      ],
      "sample": false
    },
    {
      "args": [
        [
          2,
          0,
          2,
          0
        ],
        3
      ],
      "expected": [
        [
          0,
          0,
          1
        ],
        [
          1,
          0,
          0
        ],
        [
          0,
          0,
          1
        ],
        [
          1,
          0,
          0
        ]
      ],
      "sample": false
    }
  ]
},
{
  "slug": "np-pairwise-distances",
  "name": "Pairwise Distances",
  "category": "NumPy",
  "difficulty": "Medium",
  "sub": "Broadcasting",
  "maxScore": 30,
  "successRate": "68.55%",
  "lang": "python",
  "fn": "pairwise_distances",
  "statement": "\n<p><b>Why this matters:</b> \"which training examples are closest to this one?\" is the heart of k-nearest-neighbors, k-means, and vector search (the thing under every RAG demo). Given <code>n</code> points you want the full <code>n × n</code> matrix of Euclidean distances — and you want it without writing <code>n²</code> loop iterations.</p>\n<p>Write <code>pairwise_distances(points)</code> where <code>points</code> is a 2D list (each row is one point). Return the 2D list <code>D</code> where <code>D[i][j]</code> is the Euclidean distance between point <code>i</code> and point <code>j</code>.</p>\n<p>Round every value to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>pairwise_distances([[0, 0], [3, 4]])\n-&gt;  [[0.0, 5.0], [5.0, 0.0]]</pre>\n<h3>Goal</h3>\n<p>No Python loops. The broadcasting move: <code>pts[:, None, :] - pts[None, :, :]</code> has shape <code>(n, n, d)</code> — every pair's difference vector at once. Square it, sum the last axis, <code>sqrt</code>.</p>",
  "starter": "import numpy as np\n\ndef pairwise_distances(points):\n    # points: 2D list, one point per row\n    # Return n x n 2D list of Euclidean distances, rounded to 6 decimals.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import numpy as np\n\ndef pairwise_distances(points):\n    pts = np.array(points, dtype=float)\n    # (n,1,d) - (1,n,d) broadcasts to (n,n,d): difference vector for every pair\n    diff = pts[:, None, :] - pts[None, :, :]\n    dist = np.sqrt((diff ** 2).sum(axis=-1))\n    return np.round(dist, 6).tolist()\n",
    "explanation": "<p>Inserting a length-1 axis on each side (<code>[:, None, :]</code> vs <code>[None, :, :]</code>) makes broadcasting enumerate all n·n pairs for you. This is the single most useful broadcasting pattern to internalize — it generalizes to any pairwise computation.</p>"
  },
  "cases": [
    {
      "args": [
        [
          [
            0,
            0
          ],
          [
            3,
            4
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          5.0
        ],
        [
          5.0,
          0.0
        ]
      ],
      "sample": true
    },
    {
      "args": [
        [
          [
            1,
            1
          ],
          [
            1,
            1
          ],
          [
            4,
            5
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          0.0,
          5.0
        ],
        [
          0.0,
          0.0,
          5.0
        ],
        [
          5.0,
          5.0,
          0.0
        ]
      ],
      "sample": true
    },
    {
      "args": [
        [
          [
            0
          ],
          [
            10
          ],
          [
            3
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          10.0,
          3.0
        ],
        [
          10.0,
          0.0,
          7.0
        ],
        [
          3.0,
          7.0,
          0.0
        ]
      ],
      "sample": false
    },
    {
      "args": [
        [
          [
            1,
            2,
            3
          ],
          [
            4,
            5,
            6
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          5.196152
        ],
        [
          5.196152,
          0.0
        ]
      ],
      "sample": false
    },
    {
      "args": [
        [
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            0,
            1
          ],
          [
            1,
            1
          ]
        ]
      ],
      "expected": [
        [
          0.0,
          1.0,
          1.0,
          1.414214
        ],
        [
          1.0,
          0.0,
          1.414214,
          1.0
        ],
        [
          1.0,
          1.414214,
          0.0,
          1.0
        ],
        [
          1.414214,
          1.0,
          1.0,
          0.0
        ]
      ],
      "sample": false
    }
  ]
},
{
  "slug": "np-masked-stats",
  "name": "Masked Statistics",
  "category": "NumPy",
  "difficulty": "Easy",
  "sub": "Boolean Masks",
  "maxScore": 20,
  "successRate": "81.77%",
  "lang": "python",
  "fn": "masked_stats",
  "statement": "\n<p><b>Why this matters:</b> real datasets are full of junk — sentinel values like <code>-999</code>, dropped-sensor zeros, outliers. Before training anything you filter with a <em>boolean mask</em>: an array of <code>True/False</code> that selects only the rows you trust. It's <code>Array.prototype.filter</code>, but vectorized.</p>\n<p>Write <code>masked_stats(values, threshold)</code> that looks only at values <strong>strictly greater than</strong> <code>threshold</code> and returns a dict:</p>\n<pre>{\"count\": how many passed, \"mean\": their mean, \"std\": their population std (ddof=0)}</pre>\n<p>If nothing passes the filter, return <code>{\"count\": 0, \"mean\": None, \"std\": None}</code>. Round <code>mean</code> and <code>std</code> to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>masked_stats([1, 5, 3, 8, 2], 2)  -&gt;  {\"count\": 3, \"mean\": 5.333333, \"std\": 2.054805}</pre>\n<h3>Goal</h3>\n<p>Build the mask once (<code>arr &gt; threshold</code>), index with it, and use <code>.mean()</code> / <code>.std()</code>. Note NumPy's <code>std</code> defaults to the <em>population</em> formula (ddof=0) — pandas defaults to sample (ddof=1). That mismatch is a classic interview gotcha.</p>",
  "starter": "import numpy as np\n\ndef masked_stats(values, threshold):\n    # values: list of numbers; consider only values > threshold\n    # Return {\"count\": int, \"mean\": float, \"std\": float} (population std),\n    # mean/std rounded to 6 decimals; None for mean/std when count is 0.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import numpy as np\n\ndef masked_stats(values, threshold):\n    arr = np.array(values, dtype=float)\n    kept = arr[arr > threshold]        # boolean mask -> filtered copy\n    if kept.size == 0:\n        return {\"count\": 0, \"mean\": None, \"std\": None}\n    return {\n        \"count\": int(kept.size),\n        \"mean\": round(float(kept.mean()), 6),\n        \"std\": round(float(kept.std()), 6),   # ddof=0: population std\n    }\n",
    "explanation": "<p>Boolean-mask indexing is NumPy's <code>filter()</code>. The only trap is the std convention: <code>np.std</code> divides by <code>n</code> (population), <code>pd.Series.std</code> divides by <code>n-1</code> (sample). State which one you're using, always.</p>"
  },
  "cases": [
    {
      "args": [
        [
          1,
          5,
          3,
          8,
          2
        ],
        2
      ],
      "expected": {
        "count": 3,
        "mean": 5.333333,
        "std": 2.054805
      },
      "sample": true
    },
    {
      "args": [
        [
          10,
          20,
          30
        ],
        0
      ],
      "expected": {
        "count": 3,
        "mean": 20.0,
        "std": 8.164966
      },
      "sample": true
    },
    {
      "args": [
        [
          1,
          2,
          3
        ],
        100
      ],
      "expected": {
        "count": 0,
        "mean": null,
        "std": null
      },
      "sample": false
    },
    {
      "args": [
        [
          -5,
          -2,
          -9,
          -1
        ],
        -3
      ],
      "expected": {
        "count": 2,
        "mean": -1.5,
        "std": 0.5
      },
      "sample": false
    },
    {
      "args": [
        [
          4,
          4,
          4,
          4
        ],
        3
      ],
      "expected": {
        "count": 4,
        "mean": 4.0,
        "std": 0.0
      },
      "sample": false
    },
    {
      "args": [
        [
          0.5,
          1.5,
          2.5,
          3.5
        ],
        1.0
      ],
      "expected": {
        "count": 3,
        "mean": 2.5,
        "std": 0.816497
      },
      "sample": false
    }
  ]
},
{
  "slug": "pd-groupby-revenue",
  "name": "Group and Aggregate",
  "category": "Pandas",
  "difficulty": "Easy",
  "sub": "GroupBy",
  "maxScore": 20,
  "successRate": "85.36%",
  "lang": "python",
  "fn": "revenue_by_region",
  "statement": "\n<p><b>Why this matters:</b> <code>groupby</code> is pandas' superpower and the first thing every data interview asks. It is SQL's <code>GROUP BY</code>, or <code>Object.groupBy</code> in modern JS — split rows into buckets, then aggregate each bucket.</p>\n<p>Write <code>revenue_by_region(rows)</code> where <code>rows</code> is a list of dicts like <code>{\"region\": \"west\", \"product\": \"widget\", \"revenue\": 1200.5}</code>. Return a dict mapping each region to <code>{\"total\": sum, \"avg\": mean}</code> of its revenue, both rounded to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>revenue_by_region([\n  {\"region\": \"west\", \"product\": \"a\", \"revenue\": 100},\n  {\"region\": \"west\", \"product\": \"b\", \"revenue\": 300},\n  {\"region\": \"east\", \"product\": \"a\", \"revenue\": 50},\n])\n-&gt;  {\"east\": {\"total\": 50.0, \"avg\": 50.0}, \"west\": {\"total\": 400.0, \"avg\": 200.0}}</pre>\n<h3>Goal</h3>\n<p>Build a DataFrame with <code>pd.DataFrame(rows)</code>, then <code>df.groupby(\"region\")[\"revenue\"].agg([\"sum\", \"mean\"])</code>. One groupby, no manual loops over regions.</p>",
  "starter": "import pandas as pd\n\ndef revenue_by_region(rows):\n    # rows: list of {\"region\", \"product\", \"revenue\"} dicts\n    # Return {region: {\"total\": float, \"avg\": float}} rounded to 6 decimals.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import pandas as pd\n\ndef revenue_by_region(rows):\n    df = pd.DataFrame(rows)\n    agg = df.groupby(\"region\")[\"revenue\"].agg([\"sum\", \"mean\"])\n    return {\n        region: {\"total\": round(float(r[\"sum\"]), 6), \"avg\": round(float(r[\"mean\"]), 6)}\n        for region, r in agg.iterrows()\n    }\n",
    "explanation": "<p>groupby-then-agg is the split-apply-combine pattern: split rows by key, apply <code>sum</code>/<code>mean</code> per bucket, combine into one table. The final dict comprehension just converts pandas scalars back to plain JSON-able Python.</p>"
  },
  "cases": [
    {
      "args": [
        [
          {
            "region": "west",
            "product": "a",
            "revenue": 100
          },
          {
            "region": "west",
            "product": "b",
            "revenue": 300
          },
          {
            "region": "east",
            "product": "a",
            "revenue": 50
          }
        ]
      ],
      "expected": {
        "east": {
          "total": 50.0,
          "avg": 50.0
        },
        "west": {
          "total": 400.0,
          "avg": 200.0
        }
      },
      "sample": true
    },
    {
      "args": [
        [
          {
            "region": "north",
            "product": "x",
            "revenue": 10.5
          },
          {
            "region": "north",
            "product": "y",
            "revenue": 20.25
          }
        ]
      ],
      "expected": {
        "north": {
          "total": 30.75,
          "avg": 15.375
        }
      },
      "sample": true
    },
    {
      "args": [
        [
          {
            "region": "solo",
            "product": "only",
            "revenue": 999.99
          }
        ]
      ],
      "expected": {
        "solo": {
          "total": 999.99,
          "avg": 999.99
        }
      },
      "sample": false
    },
    {
      "args": [
        [
          {
            "region": "a",
            "product": "p",
            "revenue": 1
          },
          {
            "region": "b",
            "product": "p",
            "revenue": 2
          },
          {
            "region": "a",
            "product": "q",
            "revenue": 3
          },
          {
            "region": "b",
            "product": "q",
            "revenue": 4
          },
          {
            "region": "a",
            "product": "r",
            "revenue": 5
          }
        ]
      ],
      "expected": {
        "a": {
          "total": 9.0,
          "avg": 3.0
        },
        "b": {
          "total": 6.0,
          "avg": 3.0
        }
      },
      "sample": false
    },
    {
      "args": [
        [
          {
            "region": "z",
            "product": "p",
            "revenue": 0
          },
          {
            "region": "z",
            "product": "q",
            "revenue": 0
          }
        ]
      ],
      "expected": {
        "z": {
          "total": 0.0,
          "avg": 0.0
        }
      },
      "sample": false
    }
  ]
},
{
  "slug": "pd-join-fillna",
  "name": "Join Users to Orders",
  "category": "Pandas",
  "difficulty": "Medium",
  "sub": "Merging",
  "maxScore": 25,
  "successRate": "74.88%",
  "lang": "python",
  "fn": "user_spend",
  "statement": "\n<p><b>Why this matters:</b> data never arrives in one table. You constantly <em>join</em> — users to orders, events to sessions — exactly like a SQL <code>LEFT JOIN</code>. And after a left join, users with no orders have missing values (<code>NaN</code>) that you must fill deliberately, not accidentally ship as <code>null</code>.</p>\n<p>Write <code>user_spend(users, orders)</code>. <code>users</code> is a list of <code>{\"user_id\", \"name\"}</code> dicts; <code>orders</code> is a list of <code>{\"user_id\", \"amount\"}</code> dicts (a user may have many orders or none). Left-join total spend onto users, filling users without orders with <code>0.0</code>.</p>\n<p>Return a list of <code>{\"user_id\", \"name\", \"total_spend\"}</code> dicts sorted by <code>user_id</code> ascending, with <code>total_spend</code> rounded to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>user_spend([{\"user_id\": 1, \"name\": \"Ada\"}, {\"user_id\": 2, \"name\": \"Lin\"}],\n           [{\"user_id\": 1, \"amount\": 30}, {\"user_id\": 1, \"amount\": 12.5}])\n-&gt;  [{\"user_id\": 1, \"name\": \"Ada\", \"total_spend\": 42.5},\n    {\"user_id\": 2, \"name\": \"Lin\", \"total_spend\": 0.0}]</pre>\n<h3>Goal</h3>\n<p>Aggregate orders per user first (<code>groupby(\"user_id\")[\"amount\"].sum()</code>), then <code>pd.merge(users_df, sums, on=\"user_id\", how=\"left\")</code>, then <code>.fillna(0)</code>. Merge-then-fillna is the pattern; the order of operations is the interview question.</p>",
  "starter": "import pandas as pd\n\ndef user_spend(users, orders):\n    # users: [{\"user_id\", \"name\"}], orders: [{\"user_id\", \"amount\"}]\n    # Return [{\"user_id\", \"name\", \"total_spend\"}] sorted by user_id,\n    # users without orders get 0.0, rounded to 6 decimals.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import pandas as pd\n\ndef user_spend(users, orders):\n    users_df = pd.DataFrame(users)\n    if orders:\n        sums = (pd.DataFrame(orders)\n                  .groupby(\"user_id\", as_index=False)[\"amount\"].sum()\n                  .rename(columns={\"amount\": \"total_spend\"}))\n        merged = users_df.merge(sums, on=\"user_id\", how=\"left\")\n    else:\n        merged = users_df.assign(total_spend=0.0)\n    merged[\"total_spend\"] = merged[\"total_spend\"].fillna(0.0)\n    merged = merged.sort_values(\"user_id\")\n    return [\n        {\"user_id\": int(r.user_id), \"name\": r.name_, \"total_spend\": round(float(r.total_spend), 6)}\n        for r in merged.rename(columns={\"name\": \"name_\"}).itertuples(index=False)\n    ]\n",
    "explanation": "<p>Aggregate first, join second — joining raw orders then summing also works but duplicates user rows mid-pipeline. <code>how=\"left\"</code> keeps order-less users; <code>fillna(0.0)</code> makes the missing-data decision explicit. (<code>name</code> is renamed before <code>itertuples</code> because it collides with the namedtuple's own attribute.)</p>"
  },
  "cases": [
    {
      "args": [
        [
          {
            "user_id": 1,
            "name": "Ada"
          },
          {
            "user_id": 2,
            "name": "Lin"
          }
        ],
        [
          {
            "user_id": 1,
            "amount": 30
          },
          {
            "user_id": 1,
            "amount": 12.5
          }
        ]
      ],
      "expected": [
        {
          "user_id": 1,
          "name": "Ada",
          "total_spend": 42.5
        },
        {
          "user_id": 2,
          "name": "Lin",
          "total_spend": 0.0
        }
      ],
      "sample": true
    },
    {
      "args": [
        [
          {
            "user_id": 3,
            "name": "Bo"
          }
        ],
        []
      ],
      "expected": [
        {
          "user_id": 3,
          "name": "Bo",
          "total_spend": 0.0
        }
      ],
      "sample": true
    },
    {
      "args": [
        [
          {
            "user_id": 2,
            "name": "Kim"
          },
          {
            "user_id": 1,
            "name": "Raj"
          }
        ],
        [
          {
            "user_id": 2,
            "amount": 5
          },
          {
            "user_id": 1,
            "amount": 7
          },
          {
            "user_id": 2,
            "amount": 5
          }
        ]
      ],
      "expected": [
        {
          "user_id": 1,
          "name": "Raj",
          "total_spend": 7.0
        },
        {
          "user_id": 2,
          "name": "Kim",
          "total_spend": 10.0
        }
      ],
      "sample": false
    },
    {
      "args": [
        [
          {
            "user_id": 1,
            "name": "A"
          },
          {
            "user_id": 2,
            "name": "B"
          },
          {
            "user_id": 3,
            "name": "C"
          }
        ],
        [
          {
            "user_id": 2,
            "amount": 0.1
          },
          {
            "user_id": 2,
            "amount": 0.2
          }
        ]
      ],
      "expected": [
        {
          "user_id": 1,
          "name": "A",
          "total_spend": 0.0
        },
        {
          "user_id": 2,
          "name": "B",
          "total_spend": 0.3
        },
        {
          "user_id": 3,
          "name": "C",
          "total_spend": 0.0
        }
      ],
      "sample": false
    },
    {
      "args": [
        [
          {
            "user_id": 5,
            "name": "Eve"
          }
        ],
        [
          {
            "user_id": 5,
            "amount": 100
          },
          {
            "user_id": 5,
            "amount": 200
          },
          {
            "user_id": 5,
            "amount": 300
          }
        ]
      ],
      "expected": [
        {
          "user_id": 5,
          "name": "Eve",
          "total_spend": 600.0
        }
      ],
      "sample": false
    }
  ]
},
{
  "slug": "pd-pivot-sales",
  "name": "Pivot: Long to Wide",
  "category": "Pandas",
  "difficulty": "Medium",
  "sub": "Reshaping",
  "maxScore": 25,
  "successRate": "71.60%",
  "lang": "python",
  "fn": "pivot_sales",
  "statement": "\n<p><b>Why this matters:</b> databases store data <em>long</em> (one row per observation), but humans and charts want it <em>wide</em> (months as rows, categories as columns). Converting long → wide is a <em>pivot</em> — the same reshape you do mentally every time you build an HTML table from a flat API response.</p>\n<p>Write <code>pivot_sales(rows)</code> where each row is <code>{\"month\": \"Jan\", \"category\": \"toys\", \"sales\": 120}</code>. The same month+category pair may appear multiple times — <strong>sum</strong> them. Return a nested dict <code>{month: {category: total_sales}}</code> where every month contains <strong>every category seen anywhere in the data</strong>, with <code>0.0</code> for missing combinations. Round to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>pivot_sales([\n  {\"month\": \"Jan\", \"category\": \"toys\", \"sales\": 100},\n  {\"month\": \"Feb\", \"category\": \"books\", \"sales\": 80},\n  {\"month\": \"Jan\", \"category\": \"toys\", \"sales\": 20},\n])\n-&gt;  {\"Feb\": {\"books\": 80.0, \"toys\": 0.0}, \"Jan\": {\"books\": 0.0, \"toys\": 120.0}}</pre>\n<h3>Goal</h3>\n<p>One call: <code>df.pivot_table(index=\"month\", columns=\"category\", values=\"sales\", aggfunc=\"sum\", fill_value=0)</code>. Know the difference from <code>df.pivot</code>, which crashes on duplicate index/column pairs because it cannot aggregate.</p>",
  "starter": "import pandas as pd\n\ndef pivot_sales(rows):\n    # rows: [{\"month\", \"category\", \"sales\"}], duplicates are summed\n    # Return {month: {category: total}} with 0.0 for missing combos,\n    # rounded to 6 decimals.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import pandas as pd\n\ndef pivot_sales(rows):\n    df = pd.DataFrame(rows)\n    wide = df.pivot_table(index=\"month\", columns=\"category\",\n                          values=\"sales\", aggfunc=\"sum\", fill_value=0)\n    return {\n        str(month): {str(cat): round(float(wide.loc[month, cat]), 6) for cat in wide.columns}\n        for month in wide.index\n    }\n",
    "explanation": "<p><code>pivot_table</code> = groupby on two keys + reshape + fill, in one call. <code>fill_value=0</code> handles combinations that never occurred. The interview distinction: <code>pivot</code> is a pure reshape and throws on duplicates; <code>pivot_table</code> aggregates them.</p>"
  },
  "cases": [
    {
      "args": [
        [
          {
            "month": "Jan",
            "category": "toys",
            "sales": 100
          },
          {
            "month": "Feb",
            "category": "books",
            "sales": 80
          },
          {
            "month": "Jan",
            "category": "toys",
            "sales": 20
          }
        ]
      ],
      "expected": {
        "Feb": {
          "books": 80.0,
          "toys": 0.0
        },
        "Jan": {
          "books": 0.0,
          "toys": 120.0
        }
      },
      "sample": true
    },
    {
      "args": [
        [
          {
            "month": "Mar",
            "category": "a",
            "sales": 1
          },
          {
            "month": "Mar",
            "category": "b",
            "sales": 2
          }
        ]
      ],
      "expected": {
        "Mar": {
          "a": 1.0,
          "b": 2.0
        }
      },
      "sample": true
    },
    {
      "args": [
        [
          {
            "month": "Jan",
            "category": "x",
            "sales": 5.5
          },
          {
            "month": "Feb",
            "category": "y",
            "sales": 2.25
          },
          {
            "month": "Mar",
            "category": "x",
            "sales": 1
          },
          {
            "month": "Feb",
            "category": "x",
            "sales": 3
          }
        ]
      ],
      "expected": {
        "Feb": {
          "x": 3.0,
          "y": 2.25
        },
        "Jan": {
          "x": 5.5,
          "y": 0.0
        },
        "Mar": {
          "x": 1.0,
          "y": 0.0
        }
      },
      "sample": false
    },
    {
      "args": [
        [
          {
            "month": "Dec",
            "category": "gifts",
            "sales": 500
          }
        ]
      ],
      "expected": {
        "Dec": {
          "gifts": 500.0
        }
      },
      "sample": false
    },
    {
      "args": [
        [
          {
            "month": "Q1",
            "category": "a",
            "sales": 10
          },
          {
            "month": "Q1",
            "category": "a",
            "sales": 15
          },
          {
            "month": "Q2",
            "category": "b",
            "sales": 20
          },
          {
            "month": "Q2",
            "category": "b",
            "sales": 5
          }
        ]
      ],
      "expected": {
        "Q1": {
          "a": 25.0,
          "b": 0.0
        },
        "Q2": {
          "a": 0.0,
          "b": 25.0
        }
      },
      "sample": false
    }
  ]
},
{
  "slug": "pd-resample-daily",
  "name": "Resample to Daily Totals",
  "category": "Pandas",
  "difficulty": "Medium",
  "sub": "Time Series",
  "maxScore": 30,
  "successRate": "66.91%",
  "lang": "python",
  "fn": "daily_totals",
  "statement": "\n<p><b>Why this matters:</b> event logs arrive with messy timestamps; dashboards want one number per day. <em>Resampling</em> is groupby for time — bucket timestamps into calendar days (or hours, or weeks) and aggregate each bucket. Crucially it also <strong>creates empty buckets</strong> for days with no events, which is what makes charts show the gap instead of skipping it.</p>\n<p>Write <code>daily_totals(events)</code> where each event is <code>{\"ts\": \"2024-03-01T14:30:00\", \"value\": 5}</code>. Return a list of <code>{\"date\": \"YYYY-MM-DD\", \"total\": float}</code> dicts, one per calendar day from the earliest event's day to the latest event's day <strong>inclusive — including days with zero events</strong> (total <code>0.0</code>), sorted by date. Round totals to 6 decimals. All expected outputs in the tests are rounded to 6 decimals.</p>\n<h3>Example</h3>\n<pre>daily_totals([\n  {\"ts\": \"2024-03-01T09:00:00\", \"value\": 2},\n  {\"ts\": \"2024-03-03T12:00:00\", \"value\": 7},\n  {\"ts\": \"2024-03-01T23:59:00\", \"value\": 3},\n])\n-&gt;  [{\"date\": \"2024-03-01\", \"total\": 5.0},\n    {\"date\": \"2024-03-02\", \"total\": 0.0},\n    {\"date\": \"2024-03-03\", \"total\": 7.0}]</pre>\n<h3>Goal</h3>\n<p>Parse with <code>pd.to_datetime</code>, set the timestamp as index, then <code>df.resample(\"D\")[\"value\"].sum()</code>. Resample fills the missing March 2nd for free — that's the point of using it over a plain groupby on the date string.</p>",
  "starter": "import pandas as pd\n\ndef daily_totals(events):\n    # events: [{\"ts\": ISO datetime string, \"value\": number}]\n    # Return [{\"date\": \"YYYY-MM-DD\", \"total\": float}] covering every day\n    # from first to last inclusive (0.0 for empty days), rounded to 6 decimals.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import pandas as pd\n\ndef daily_totals(events):\n    df = pd.DataFrame(events)\n    df[\"ts\"] = pd.to_datetime(df[\"ts\"])\n    daily = df.set_index(\"ts\").resample(\"D\")[\"value\"].sum()  # empty days -> 0\n    return [\n        {\"date\": ts.strftime(\"%Y-%m-%d\"), \"total\": round(float(v), 6)}\n        for ts, v in daily.items()\n    ]\n",
    "explanation": "<p><code>resample(\"D\")</code> builds a complete daily DatetimeIndex spanning min→max and sums each bucket; days with no rows aggregate over an empty set, and <code>sum()</code> of empty is 0. A groupby on <code>ts.dt.date</code> would silently drop the empty days — the classic time-series bug.</p>"
  },
  "cases": [
    {
      "args": [
        [
          {
            "ts": "2024-03-01T09:00:00",
            "value": 2
          },
          {
            "ts": "2024-03-03T12:00:00",
            "value": 7
          },
          {
            "ts": "2024-03-01T23:59:00",
            "value": 3
          }
        ]
      ],
      "expected": [
        {
          "date": "2024-03-01",
          "total": 5.0
        },
        {
          "date": "2024-03-02",
          "total": 0.0
        },
        {
          "date": "2024-03-03",
          "total": 7.0
        }
      ],
      "sample": true
    },
    {
      "args": [
        [
          {
            "ts": "2024-01-15T00:00:00",
            "value": 10
          }
        ]
      ],
      "expected": [
        {
          "date": "2024-01-15",
          "total": 10.0
        }
      ],
      "sample": true
    },
    {
      "args": [
        [
          {
            "ts": "2024-06-10T08:00:00",
            "value": 1.5
          },
          {
            "ts": "2024-06-10T20:00:00",
            "value": 2.5
          }
        ]
      ],
      "expected": [
        {
          "date": "2024-06-10",
          "total": 4.0
        }
      ],
      "sample": false
    },
    {
      "args": [
        [
          {
            "ts": "2024-02-28T12:00:00",
            "value": 4
          },
          {
            "ts": "2024-03-01T12:00:00",
            "value": 6
          }
        ]
      ],
      "expected": [
        {
          "date": "2024-02-28",
          "total": 4.0
        },
        {
          "date": "2024-02-29",
          "total": 0.0
        },
        {
          "date": "2024-03-01",
          "total": 6.0
        }
      ],
      "sample": false
    },
    {
      "args": [
        [
          {
            "ts": "2024-11-05T10:00:00",
            "value": 100
          },
          {
            "ts": "2024-11-01T10:00:00",
            "value": 50
          },
          {
            "ts": "2024-11-03T10:00:00",
            "value": 25
          }
        ]
      ],
      "expected": [
        {
          "date": "2024-11-01",
          "total": 50.0
        },
        {
          "date": "2024-11-02",
          "total": 0.0
        },
        {
          "date": "2024-11-03",
          "total": 25.0
        },
        {
          "date": "2024-11-04",
          "total": 0.0
        },
        {
          "date": "2024-11-05",
          "total": 100.0
        }
      ],
      "sample": false
    }
  ]
},
{
  "slug": "pd-top-n-per-group",
  "name": "Top N per Group",
  "category": "Pandas",
  "difficulty": "Medium",
  "sub": "GroupBy",
  "maxScore": 30,
  "successRate": "69.24%",
  "lang": "python",
  "fn": "top_scorers",
  "statement": "\n<p><b>Why this matters:</b> \"top 3 products per region\", \"latest 5 events per user\" — the top-N-per-group query is everywhere, and it's awkward in SQL (window functions) but two chained calls in pandas. It also teaches the most important habit in data work: <strong>sort first, then group</strong>.</p>\n<p>Write <code>top_scorers(rows, n)</code> where each row is <code>{\"team\": \"red\", \"player\": \"ana\", \"points\": 31}</code>. For each team keep its top <code>n</code> players by points (if a team has fewer than <code>n</code> players, keep them all). Break point ties by player name ascending (alphabetical). Return a flat list of the kept rows sorted by team ascending, then points descending, then player ascending.</p>\n<h3>Example</h3>\n<pre>top_scorers([\n  {\"team\": \"red\", \"player\": \"ana\", \"points\": 31},\n  {\"team\": \"red\", \"player\": \"bo\",  \"points\": 12},\n  {\"team\": \"red\", \"player\": \"cy\",  \"points\": 25},\n  {\"team\": \"blu\", \"player\": \"dee\", \"points\": 9},\n], 2)\n-&gt;  [{\"team\": \"blu\", \"player\": \"dee\", \"points\": 9},\n    {\"team\": \"red\", \"player\": \"ana\", \"points\": 31},\n    {\"team\": \"red\", \"player\": \"cy\", \"points\": 25}]</pre>\n<h3>Goal</h3>\n<p>Sort by <code>[\"team\", \"points\", \"player\"]</code> with <code>ascending=[True, False, True]</code>, then <code>groupby(\"team\").head(n)</code>. <code>head</code> after a sort respects the sorted order inside each group — that's the whole trick.</p>",
  "starter": "import pandas as pd\n\ndef top_scorers(rows, n):\n    # rows: [{\"team\", \"player\", \"points\"}]\n    # Return top n per team by points (ties: player name asc),\n    # flat list sorted by team asc, points desc, player asc.\n    # Write your code here\n    pass\n",
  "solution": {
    "code": "import pandas as pd\n\ndef top_scorers(rows, n):\n    df = pd.DataFrame(rows)\n    df = df.sort_values([\"team\", \"points\", \"player\"], ascending=[True, False, True])\n    top = df.groupby(\"team\").head(n)   # first n rows per team, in sorted order\n    return [\n        {\"team\": t, \"player\": p, \"points\": int(pt) if float(pt).is_integer() else float(pt)}\n        for t, p, pt in zip(top[\"team\"], top[\"player\"], top[\"points\"])\n    ]\n",
    "explanation": "<p><code>groupby(...).head(n)</code> keeps each group's first n rows <em>in current row order</em>, so pre-sorting by points makes it \"top n\". This beats <code>nlargest</code> per group because it preserves your tie-breaking sort exactly and returns a flat frame, no index surgery.</p>"
  },
  "cases": [
    {
      "args": [
        [
          {
            "team": "red",
            "player": "ana",
            "points": 31
          },
          {
            "team": "red",
            "player": "bo",
            "points": 12
          },
          {
            "team": "red",
            "player": "cy",
            "points": 25
          },
          {
            "team": "blu",
            "player": "dee",
            "points": 9
          }
        ],
        2
      ],
      "expected": [
        {
          "team": "blu",
          "player": "dee",
          "points": 9
        },
        {
          "team": "red",
          "player": "ana",
          "points": 31
        },
        {
          "team": "red",
          "player": "cy",
          "points": 25
        }
      ],
      "sample": true
    },
    {
      "args": [
        [
          {
            "team": "a",
            "player": "x",
            "points": 5
          }
        ],
        3
      ],
      "expected": [
        {
          "team": "a",
          "player": "x",
          "points": 5
        }
      ],
      "sample": true
    },
    {
      "args": [
        [
          {
            "team": "t1",
            "player": "b",
            "points": 10
          },
          {
            "team": "t1",
            "player": "a",
            "points": 10
          },
          {
            "team": "t1",
            "player": "c",
            "points": 10
          }
        ],
        2
      ],
      "expected": [
        {
          "team": "t1",
          "player": "a",
          "points": 10
        },
        {
          "team": "t1",
          "player": "b",
          "points": 10
        }
      ],
      "sample": false
    },
    {
      "args": [
        [
          {
            "team": "z",
            "player": "p1",
            "points": 1
          },
          {
            "team": "y",
            "player": "p2",
            "points": 2
          },
          {
            "team": "x",
            "player": "p3",
            "points": 3
          }
        ],
        1
      ],
      "expected": [
        {
          "team": "x",
          "player": "p3",
          "points": 3
        },
        {
          "team": "y",
          "player": "p2",
          "points": 2
        },
        {
          "team": "z",
          "player": "p1",
          "points": 1
        }
      ],
      "sample": false
    },
    {
      "args": [
        [
          {
            "team": "m",
            "player": "a",
            "points": 50
          },
          {
            "team": "m",
            "player": "b",
            "points": 40
          },
          {
            "team": "m",
            "player": "c",
            "points": 30
          },
          {
            "team": "m",
            "player": "d",
            "points": 20
          },
          {
            "team": "n",
            "player": "e",
            "points": 45
          },
          {
            "team": "n",
            "player": "f",
            "points": 35
          }
        ],
        3
      ],
      "expected": [
        {
          "team": "m",
          "player": "a",
          "points": 50
        },
        {
          "team": "m",
          "player": "b",
          "points": 40
        },
        {
          "team": "m",
          "player": "c",
          "points": 30
        },
        {
          "team": "n",
          "player": "e",
          "points": 45
        },
        {
          "team": "n",
          "player": "f",
          "points": 35
        }
      ],
      "sample": false
    }
  ]
}
  ];
  for (var i = 0; i < problems.length; i++) M.push(problems[i]);
})();
