// Reference Python solutions for the 46 Special Interview Questions.
// Every solution defines the SAME function name as the JS starter (the grader
// calls p.fn directly in Pyodide) and was validated against the problem's own
// test cases with CPython before being embedded here.
// Consumed by app.js: the Best Solution tab shows the entry matching the
// currently selected language.
window.PR_SOLUTIONS_PY = {
  "apple-stocks": {
    code: "# Greedy one-pass: track the cheapest buy so far and the best profit so far.\n# Update profit BEFORE the min so we never buy and sell in the same minute.\n# O(n) time, O(1) space.\ndef getMaxProfit(prices):\n    if len(prices) < 2:\n        raise ValueError('Need at least 2 prices')\n    min_price = prices[0]\n    max_profit = prices[1] - prices[0]\n    for current in prices[1:]:\n        max_profit = max(max_profit, current - min_price)\n        min_price = min(min_price, current)\n    return max_profit",
    explanation: "<p>Greedy one-pass: track the cheapest buy so far and the best profit so far. Update profit BEFORE the min so we never buy and sell in the same minute. O(n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>getMaxProfit(...)</code> directly, so keep it unchanged.</p>",
  },
  "product-of-all-other-numbers": {
    code: "# Two passes, no division (division dies on zeros):\n# pass 1 stores the product of everything BEFORE each index,\n# pass 2 multiplies in the product of everything AFTER it.\n# O(n) time, O(n) for the output.\ndef getProductsOfAllIntsExceptAtIndex(nums):\n    products = [1] * len(nums)\n    before = 1\n    for i in range(len(nums)):\n        products[i] = before\n        before *= nums[i]\n    after = 1\n    for i in range(len(nums) - 1, -1, -1):\n        products[i] *= after\n        after *= nums[i]\n    return products",
    explanation: "<p>Two passes, no division (division dies on zeros): pass 1 stores the product of everything BEFORE each index, pass 2 multiplies in the product of everything AFTER it. O(n) time, O(n) for the output.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>getProductsOfAllIntsExceptAtIndex(...)</code> directly, so keep it unchanged.</p>",
  },
  "highest-product-of-3": {
    code: "# Track the extremes as we sweep: highest/lowest single value,\n# highest/lowest pair product (two big negatives can beat two positives).\n# O(n) time, O(1) space.\ndef highestProductOf3(nums):\n    highest = max(nums[0], nums[1])\n    lowest = min(nums[0], nums[1])\n    highest_2 = lowest_2 = nums[0] * nums[1]\n    highest_3 = nums[0] * nums[1] * nums[2]\n    for current in nums[2:]:\n        highest_3 = max(highest_3, current * highest_2, current * lowest_2)\n        highest_2 = max(highest_2, current * highest, current * lowest)\n        lowest_2 = min(lowest_2, current * highest, current * lowest)\n        highest = max(highest, current)\n        lowest = min(lowest, current)\n    return highest_3",
    explanation: "<p>Track the extremes as we sweep: highest/lowest single value, highest/lowest pair product (two big negatives can beat two positives). O(n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>highestProductOf3(...)</code> directly, so keep it unchanged.</p>",
  },
  "merging-meeting-times": {
    code: "# Sort by start time, then sweep: each meeting either overlaps the\n# last merged block (extend its end) or starts a new block.\n# O(n log n) time for the sort.\ndef mergeRanges(meetings):\n    sorted_meetings = sorted(meetings, key=lambda m: m['startTime'])\n    merged = []\n    for m in sorted_meetings:\n        if merged and m['startTime'] <= merged[-1]['endTime']:\n            merged[-1]['endTime'] = max(merged[-1]['endTime'], m['endTime'])\n        else:\n            merged.append(dict(m))\n    return merged",
    explanation: "<p>Sort by start time, then sweep: each meeting either overlaps the last merged block (extend its end) or starts a new block. O(n log n) time for the sort.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>mergeRanges(...)</code> directly, so keep it unchanged.</p>",
  },
  "making-change": {
    code: "# Classic unbounded-coin DP. ways[a] counts combinations that make amount a.\n# Looping coins on the OUTSIDE counts combinations, not permutations.\n# O(amount * coins) time, O(amount) space.\ndef changePossibilities(amount, denominations):\n    ways = [0] * (amount + 1)\n    ways[0] = 1\n    for coin in denominations:\n        for higher in range(coin, amount + 1):\n            ways[higher] += ways[higher - coin]\n    return ways[amount]",
    explanation: "<p>Classic unbounded-coin DP. ways[a] counts combinations that make amount a. Looping coins on the OUTSIDE counts combinations, not permutations. O(amount * coins) time, O(amount) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>changePossibilities(...)</code> directly, so keep it unchanged.</p>",
  },
  "rectangular-love": {
    code: "# Overlap per axis: the intersection starts at the larger left edge and\n# ends at the smaller right edge. Positive width AND height = real overlap.\n# O(1) time.\ndef find_range_overlap(p1, l1, p2, l2):\n    highest_start = max(p1, p2)\n    lowest_end = min(p1 + l1, p2 + l2)\n    if highest_start >= lowest_end:\n        return None, None\n    return highest_start, lowest_end - highest_start\n\ndef findRectangularOverlap(r1, r2):\n    x, w = find_range_overlap(r1['leftX'], r1['width'], r2['leftX'], r2['width'])\n    y, h = find_range_overlap(r1['bottomY'], r1['height'], r2['bottomY'], r2['height'])\n    if not w or not h:\n        return {'leftX': None, 'bottomY': None, 'width': None, 'height': None}\n    return {'leftX': x, 'bottomY': y, 'width': w, 'height': h}",
    explanation: "<p>Overlap per axis: the intersection starts at the larger left edge and ends at the smaller right edge. Positive width AND height = real overlap. O(1) time.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findRectangularOverlap(...)</code> directly, so keep it unchanged.</p>",
  },
  "temperature-tracker": {
    code: "# Keep running aggregates instead of storing every reading:\n# max, min, sum/count for the mean, and a counts dict for the mode.\n# O(n) over the readings, O(1)-ish space (count table).\ndef tempStats(temps):\n    counts = {}\n    mx, mn, total, mode, best = float('-inf'), float('inf'), 0, None, 0\n    for t in temps:\n        mx, mn, total = max(mx, t), min(mn, t), total + t\n        counts[t] = counts.get(t, 0) + 1\n        if counts[t] > best or (counts[t] == best and t < mode):\n            best, mode = counts[t], t\n    return {'max': mx, 'min': mn, 'mean': total / len(temps), 'mode': mode}",
    explanation: "<p>Keep running aggregates instead of storing every reading: max, min, sum/count for the mean, and a counts dict for the mode. O(n) over the readings, O(1)-ish space (count table).</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>tempStats(...)</code> directly, so keep it unchanged.</p>",
  },
  "balanced-binary-tree": {
    code: "# Iterative DFS collecting the depth of every leaf; superbalanced means\n# no two leaf depths differ by more than 1, so bail once we see a spread > 1\n# or a third distinct depth. O(n) time, O(n) space worst case.\ndef isBalanced(root):\n    if not root:\n        return True\n    depths, nodes = [], [(root, 0)]\n    while nodes:\n        node, depth = nodes.pop()\n        if not node['left'] and not node['right']:\n            if depth not in depths:\n                depths.append(depth)\n                if len(depths) > 2 or (len(depths) == 2 and abs(depths[0] - depths[1]) > 1):\n                    return False\n        else:\n            if node['left']:\n                nodes.append((node['left'], depth + 1))\n            if node['right']:\n                nodes.append((node['right'], depth + 1))\n    return True",
    explanation: "<p>Iterative DFS collecting the depth of every leaf; superbalanced means no two leaf depths differ by more than 1, so bail once we see a spread &gt; 1 or a third distinct depth. O(n) time, O(n) space worst case.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>isBalanced(...)</code> directly, so keep it unchanged.</p>",
  },
  "bst-checker": {
    code: "# Iterative DFS carrying (lower, upper) bounds for every node.\n# A node is legal if it sits strictly inside its inherited window;\n# children narrow the window. O(n) time, O(n) space worst case.\ndef isBinarySearchTree(root):\n    stack = [(root, float('-inf'), float('inf'))]\n    while stack:\n        node, lo, hi = stack.pop()\n        if not node:\n            continue\n        if node['value'] <= lo or node['value'] >= hi:\n            return False\n        stack.append((node['left'], lo, node['value']))\n        stack.append((node['right'], node['value'], hi))\n    return True",
    explanation: "<p>Iterative DFS carrying (lower, upper) bounds for every node. A node is legal if it sits strictly inside its inherited window; children narrow the window. O(n) time, O(n) space worst case.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>isBinarySearchTree(...)</code> directly, so keep it unchanged.</p>",
  },
  "second-largest-bst": {
    code: "# The largest node is the rightmost. The second largest is either its\n# parent (no left subtree) or the rightmost node of its left subtree.\n# One walk down the right spine: O(h) time, O(1) space.\ndef find_largest(node):\n    while node['right']:\n        node = node['right']\n    return node['value']\n\ndef findSecondLargest(root):\n    current = root\n    while current:\n        if current['left'] and not current['right']:\n            return find_largest(current['left'])\n        r = current['right']\n        if r and not r['left'] and not r['right']:\n            return current['value']\n        current = current['right']",
    explanation: "<p>The largest node is the rightmost. The second largest is either its parent (no left subtree) or the rightmost node of its left subtree. One walk down the right spine: O(h) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findSecondLargest(...)</code> directly, so keep it unchanged.</p>",
  },
  "million-gazillion": {
    code: "# Build a trie: each character is a dict level, '*' marks end-of-word.\n# Shared prefixes are stored once, which is the whole point.\n# O(total characters) time and space.\ndef buildTrie(words):\n    root = {}\n    for word in words:\n        node = root\n        for char in word:\n            node = node.setdefault(char, {})\n        node['*'] = True\n    return root",
    explanation: "<p>Build a trie: each character is a dict level, &#x27;*&#x27; marks end-of-word. Shared prefixes are stored once, which is the whole point. O(total characters) time and space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>buildTrie(...)</code> directly, so keep it unchanged.</p>",
  },
  "find-in-ordered-set": {
    code: "# Textbook binary search on a sorted list: halve the window each step.\n# floor_index/ceiling_index stay OUTSIDE the remaining candidates.\n# O(log n) time, O(1) space.\ndef binarySearch(target, nums):\n    floor_i, ceil_i = -1, len(nums)\n    while floor_i + 1 < ceil_i:\n        guess_i = floor_i + (ceil_i - floor_i) // 2\n        guess = nums[guess_i]\n        if guess == target:\n            return True\n        if guess > target:\n            ceil_i = guess_i\n        else:\n            floor_i = guess_i\n    return False",
    explanation: "<p>Textbook binary search on a sorted list: halve the window each step. floor_index/ceiling_index stay OUTSIDE the remaining candidates. O(log n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>binarySearch(...)</code> directly, so keep it unchanged.</p>",
  },
  "find-rotation-point": {
    code: "# Binary search using the first word as a pivot: words >= first word are\n# in the left (pre-rotation) half, smaller words are past the rotation point.\n# O(log n) time, O(1) space.\ndef findRotationPoint(words):\n    first = words[0]\n    lo, hi = 0, len(words) - 1\n    while lo < hi:\n        mid = lo + (hi - lo) // 2\n        if words[mid] >= first:\n            lo = mid\n        else:\n            hi = mid\n        if lo + 1 == hi:\n            break\n    return hi",
    explanation: "<p>Binary search using the first word as a pivot: words &gt;= first word are in the left (pre-rotation) half, smaller words are past the rotation point. O(log n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findRotationPoint(...)</code> directly, so keep it unchanged.</p>",
  },
  "inflight-entertainment": {
    code: "# One pass with a set of seen movie lengths: for each movie, check if\n# its complement (flight - movie) was already seen. Set, not sorting,\n# so it stays O(n) time / O(n) space and never reuses one movie twice.\ndef canTwoMoviesFillFlight(flight_length, movie_lengths):\n    seen = set()\n    for length in movie_lengths:\n        if flight_length - length in seen:\n            return True\n        seen.add(length)\n    return False",
    explanation: "<p>One pass with a set of seen movie lengths: for each movie, check if its complement (flight - movie) was already seen. Set, not sorting, so it stays O(n) time / O(n) space and never reuses one movie twice.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>canTwoMoviesFillFlight(...)</code> directly, so keep it unchanged.</p>",
  },
  "nth-fibonacci": {
    code: "# Bottom-up iteration keeping only the previous two values.\n# O(n) time, O(1) space - no recursion, no exponential blowup.\ndef fib(n):\n    if n < 0:\n        raise ValueError('Index cannot be negative')\n    if n in (0, 1):\n        return n\n    prev_prev, prev = 0, 1\n    for _ in range(2, n + 1):\n        prev_prev, prev = prev, prev + prev_prev\n    return prev",
    explanation: "<p>Bottom-up iteration keeping only the previous two values. O(n) time, O(1) space - no recursion, no exponential blowup.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>fib(...)</code> directly, so keep it unchanged.</p>",
  },
  "cake-thief": {
    code: "# Unbounded knapsack DP: best value at every capacity 0..capacity.\n# A weight-0, value>0 cake means infinite value (guard first).\n# O(n * capacity) time, O(capacity) space.\ndef maxDuffelBagValue(cake_types, capacity):\n    best = [0] * (capacity + 1)\n    for cap in range(capacity + 1):\n        current = 0\n        for cake in cake_types:\n            w, v = cake['weight'], cake['value']\n            if w == 0 and v != 0:\n                return float('inf')\n            if 0 < w <= cap:\n                current = max(current, v + best[cap - w])\n        best[cap] = current\n    return best[capacity]",
    explanation: "<p>Unbounded knapsack DP: best value at every capacity 0..capacity. A weight-0, value&gt;0 cake means infinite value (guard first). O(n * capacity) time, O(capacity) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>maxDuffelBagValue(...)</code> directly, so keep it unchanged.</p>",
  },
  "javascript-scope": {
    code: "# The JS version is a closure gotcha (var vs let in a loop).\n# Python closures capture variables late too - the fix is the same idea:\n# bind the loop value per iteration (default-arg trick).\n# Python has the same late-binding gotcha in closures:\n# fns = [lambda: i for i in range(3)]  ->  all return 2\ndef runFunctions():\n    fns = [lambda i=i: i for i in range(3)]   # default arg captures the value\n    return [f() for f in fns]",
    explanation: "<p>The JS version is a closure gotcha (var vs let in a loop). Python closures capture variables late too - the fix is the same idea: bind the loop value per iteration (default-arg trick).</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>runFunctions(...)</code> directly, so keep it unchanged.</p>",
  },
  "whats-wrong-with-this-javascript": {
    code: "# The JS bug is a shared mutable object captured by every closure.\n# Build a fresh record per name so nothing aliases.\n# O(n) time.\ndef getGreetings(names):\n    return [{'name': n, 'greeting': f'Hello, {n}!'} for n in names]",
    explanation: "<p>The JS bug is a shared mutable object captured by every closure. Build a fresh record per name so nothing aliases. O(n) time.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>getGreetings(...)</code> directly, so keep it unchanged.</p>",
  },
  "queue-two-stacks": {
    code: "# Queue from two stacks: push onto in_stack, pop from out_stack,\n# refilling out_stack (reversing order) only when it runs dry.\n# Each element moves at most twice: amortized O(1) per op.\ndef runQueue(ops):\n    in_stack, out_stack, results = [], [], []\n    for op in ops:\n        if op[0] == 'enqueue':\n            in_stack.append(op[1])\n        else:\n            if not out_stack:\n                while in_stack:\n                    out_stack.append(in_stack.pop())\n            results.append(out_stack.pop())\n    return results",
    explanation: "<p>Queue from two stacks: push onto in_stack, pop from out_stack, refilling out_stack (reversing order) only when it runs dry. Each element moves at most twice: amortized O(1) per op.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>runQueue(...)</code> directly, so keep it unchanged.</p>",
  },
  "largest-stack": {
    code: "# Keep a second stack of 'max so far' alongside the real stack.\n# Push/pop update both, so getMax is a peek: O(1) for every operation.\ndef runMaxStack(ops):\n    stack, maxes, results = [], [], []\n    for op in ops:\n        if op[0] == 'push':\n            stack.append(op[1])\n            if not maxes or op[1] >= maxes[-1]:\n                maxes.append(op[1])\n        elif op[0] == 'pop':\n            item = stack.pop() if stack else None\n            if maxes and item == maxes[-1]:\n                maxes.pop()\n            results.append(item)\n        else:\n            results.append(maxes[-1] if maxes else None)\n    return results",
    explanation: "<p>Keep a second stack of &#x27;max so far&#x27; alongside the real stack. Push/pop update both, so getMax is a peek: O(1) for every operation.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>runMaxStack(...)</code> directly, so keep it unchanged.</p>",
  },
  "stolen-breakfast-drone": {
    code: "# XOR everything together: pairs cancel to 0, leaving the unique ID.\n# O(n) time, O(1) space - no dict needed.\ndef findUniqueDeliveryId(delivery_ids):\n    unique = 0\n    for d in delivery_ids:\n        unique ^= d\n    return unique",
    explanation: "<p>XOR everything together: pairs cancel to 0, leaving the unique ID. O(n) time, O(1) space - no dict needed.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findUniqueDeliveryId(...)</code> directly, so keep it unchanged.</p>",
  },
  "delete-node": {
    code: "# Interview Cake trick: you can't unlink without the previous node, but you\n# CAN copy the next node's value in and skip it. Here modeled on a list:\n# overwrite-and-splice. O(n) for the list copy.\ndef deleteNodeAt(values, index):\n    head = None\n    for v in reversed(values):\n        head = {'value': v, 'next': head}\n    node = head\n    for _ in range(index):\n        node = node['next']\n    if not node['next']:\n        raise ValueError('Cannot delete the last node with this trick')\n    node['value'] = node['next']['value']\n    node['next'] = node['next']['next']\n    out, n = [], head\n    while n:\n        out.append(n['value'])\n        n = n['next']\n    return out",
    explanation: "<p>Interview Cake trick: you can&#x27;t unlink without the previous node, but you CAN copy the next node&#x27;s value in and skip it. Here modeled on a list: overwrite-and-splice. O(n) for the list copy.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>deleteNodeAt(...)</code> directly, so keep it unchanged.</p>",
  },
  "linked-list-cycle": {
    code: "# Floyd's tortoise-and-hare: slow moves 1, fast moves 2; they meet\n# iff there is a cycle. Nodes are built from the (values, cycle_to) spec.\n# O(n) time, O(1) extra space beyond the list itself.\ndef containsCycle(values, cycle_index):\n    if not values:\n        return False\n    nodes = [{'value': v, 'next': None} for v in values]\n    for i in range(len(nodes) - 1):\n        nodes[i]['next'] = nodes[i + 1]\n    if cycle_index >= 0:\n        nodes[-1]['next'] = nodes[cycle_index]\n    slow = fast = nodes[0]\n    while fast and fast['next']:\n        slow = slow['next']\n        fast = fast['next']['next']\n        if slow is fast:\n            return True\n    return False",
    explanation: "<p>Floyd&#x27;s tortoise-and-hare: slow moves 1, fast moves 2; they meet iff there is a cycle. Nodes are built from the (values, cycle_to) spec. O(n) time, O(1) extra space beyond the list itself.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>containsCycle(...)</code> directly, so keep it unchanged.</p>",
  },
  "reverse-linked-list": {
    code: "# Classic pointer reversal: walk once, flipping each .next to point\n# backwards, carrying (prev, current). O(n) time, O(1) space.\ndef reverseList(values):\n    head = None\n    for v in reversed(values):\n        head = {'value': v, 'next': head}\n    prev, cur = None, head\n    while cur:\n        nxt = cur['next']\n        cur['next'] = prev\n        prev, cur = cur, nxt\n    out, n = [], prev\n    while n:\n        out.append(n['value'])\n        n = n['next']\n    return out",
    explanation: "<p>Classic pointer reversal: walk once, flipping each .next to point backwards, carrying (prev, current). O(n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>reverseList(...)</code> directly, so keep it unchanged.</p>",
  },
  "kth-to-last-node": {
    code: "# Two pointers k apart: advance the lead k steps, then move both until\n# the lead falls off - the trailer is the kth-to-last.\n# O(n) time, O(1) space, one pass.\ndef kthToLastNode(k, values):\n    head = None\n    for v in reversed(values):\n        head = {'value': v, 'next': head}\n    left = right = head\n    for _ in range(k - 1):\n        if not right:\n            raise ValueError('k is larger than the list length')\n        right = right['next']\n    if not right:\n        raise ValueError('k is larger than the list length')\n    while right['next']:\n        left, right = left['next'], right['next']\n    return left['value']",
    explanation: "<p>Two pointers k apart: advance the lead k steps, then move both until the lead falls off - the trailer is the kth-to-last. O(n) time, O(1) space, one pass.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>kthToLastNode(...)</code> directly, so keep it unchanged.</p>",
  },
  "reverse-string-in-place": {
    code: "# Two pointers swapping outside-in until they cross.\n# O(n) time, O(1) extra space - mutates the list it is given.\ndef reverseCharacters(chars):\n    left, right = 0, len(chars) - 1\n    while left < right:\n        chars[left], chars[right] = chars[right], chars[left]\n        left += 1\n        right -= 1\n    return chars",
    explanation: "<p>Two pointers swapping outside-in until they cross. O(n) time, O(1) extra space - mutates the list it is given.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>reverseCharacters(...)</code> directly, so keep it unchanged.</p>",
  },
  "reverse-words": {
    code: "# Reverse ALL characters, then re-reverse each word in place -\n# two wrongs make a right. O(n) time, O(1) extra space.\ndef _rev(chars, i, j):\n    while i < j:\n        chars[i], chars[j] = chars[j], chars[i]\n        i += 1\n        j -= 1\n\ndef reverseWords(message):\n    _rev(message, 0, len(message) - 1)\n    start = 0\n    for i in range(len(message) + 1):\n        if i == len(message) or message[i] == ' ':\n            _rev(message, start, i - 1)\n            start = i + 1\n    return message",
    explanation: "<p>Reverse ALL characters, then re-reverse each word in place - two wrongs make a right. O(n) time, O(1) extra space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>reverseWords(...)</code> directly, so keep it unchanged.</p>",
  },
  "parenthesis-matching": {
    code: "# Count nesting depth from the opening paren: +1 on '(', -1 on ')';\n# depth 0 is the matching closer. O(n) time, O(1) space.\ndef getClosingParen(sentence, opening_paren_index):\n    open_nested = 0\n    for position in range(opening_paren_index + 1, len(sentence)):\n        char = sentence[position]\n        if char == '(':\n            open_nested += 1\n        elif char == ')':\n            if open_nested == 0:\n                return position\n            open_nested -= 1\n    raise ValueError('No closing parenthesis :(')",
    explanation: "<p>Count nesting depth from the opening paren: +1 on &#x27;(&#x27;, -1 on &#x27;)&#x27;; depth 0 is the matching closer. O(n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>getClosingParen(...)</code> directly, so keep it unchanged.</p>",
  },
  "bracket-validator": {
    code: "# Stack of expected closers: push on open, pop-and-match on close.\n# Valid iff every closer matches and the stack ends empty.\n# O(n) time, O(n) space.\ndef isValid(code):\n    pairs = {'(': ')', '[': ']', '{': '}'}\n    stack = []\n    for char in code:\n        if char in pairs:\n            stack.append(char)\n        elif char in pairs.values():\n            if not stack or pairs[stack.pop()] != char:\n                return False\n    return not stack",
    explanation: "<p>Stack of expected closers: push on open, pop-and-match on close. Valid iff every closer matches and the stack ends empty. O(n) time, O(n) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>isValid(...)</code> directly, so keep it unchanged.</p>",
  },
  "permutation-palindrome": {
    code: "# A permutation can be a palindrome iff at most ONE character has an\n# odd count. Toggle membership in a set; check its size.\n# O(n) time, O(1) space (bounded alphabet).\ndef hasPalindromePermutation(the_string):\n    unpaired = set()\n    for char in the_string:\n        if char in unpaired:\n            unpaired.remove(char)\n        else:\n            unpaired.add(char)\n    return len(unpaired) <= 1",
    explanation: "<p>A permutation can be a palindrome iff at most ONE character has an odd count. Toggle membership in a set; check its size. O(n) time, O(1) space (bounded alphabet).</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>hasPalindromePermutation(...)</code> directly, so keep it unchanged.</p>",
  },
  "recursive-string-permutations": {
    code: "# Recursion on 'all but the last char': take each shorter permutation\n# and insert the last char in every gap. Set kills duplicate letters' repeats;\n# sorted() gives the deterministic order the grader expects.\ndef getPermutations(string):\n    if len(string) <= 1:\n        return [string]\n    all_but_last, last = string[:-1], string[-1]\n    perms = set()\n    for p in getPermutations(all_but_last):\n        for i in range(len(p) + 1):\n            perms.add(p[:i] + last + p[i:])\n    return sorted(perms)",
    explanation: "<p>Recursion on &#x27;all but the last char&#x27;: take each shorter permutation and insert the last char in every gap. Set kills duplicate letters&#x27; repeats; sorted() gives the deterministic order the grader expects.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>getPermutations(...)</code> directly, so keep it unchanged.</p>",
  },
  "top-scores": {
    code: "# Counting sort: scores are bounded by highest_possible, so bucket-count\n# then read the buckets high-to-low. O(n + k) time - beats comparison sorts.\ndef sortScores(unordered_scores, highest_possible_score):\n    counts = [0] * (highest_possible_score + 1)\n    for s in unordered_scores:\n        counts[s] += 1\n    out = []\n    for score in range(highest_possible_score, -1, -1):\n        out.extend([score] * counts[score])\n    return out",
    explanation: "<p>Counting sort: scores are bounded by highest_possible, so bucket-count then read the buckets high-to-low. O(n + k) time - beats comparison sorts.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>sortScores(...)</code> directly, so keep it unchanged.</p>",
  },
  "which-appears-twice": {
    code: "# Triangular-number math: sum(1..n) is known, so the repeat is\n# actual_sum - expected_sum. O(n) time, O(1) space, no dict.\ndef findRepeat(numbers):\n    n = len(numbers) - 1\n    return sum(numbers) - n * (n + 1) // 2",
    explanation: "<p>Triangular-number math: sum(1..n) is known, so the repeat is actual_sum - expected_sum. O(n) time, O(1) space, no dict.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findRepeat(...)</code> directly, so keep it unchanged.</p>",
  },
  "word-cloud-data": {
    code: "# Hand-rolled tokenizer: walk the string, letters/apostrophes/hyphens\n# extend the current word, anything else closes it. Lowercase on conflict\n# so 'After' and 'after' merge. O(n) time.\nimport re\n\ndef wordCloud(text):\n    counts = {}\n    for word in re.findall(r\"[a-z0-9]+(?:['-][a-z0-9]+)*\", text.lower()):\n        counts[word] = counts.get(word, 0) + 1\n    return counts",
    explanation: "<p>Hand-rolled tokenizer: walk the string, letters/apostrophes/hyphens extend the current word, anything else closes it. Lowercase on conflict so &#x27;After&#x27; and &#x27;after&#x27; merge. O(n) time.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>wordCloud(...)</code> directly, so keep it unchanged.</p>",
  },
  "in-place-shuffle": {
    code: "# Fisher-Yates: at index i, swap with a uniform random index in [i, n).\n# The injected 'random' floats make it deterministic for grading.\n# O(n) time, O(1) space, unbiased.\nimport math\n\ndef shuffle(the_array, randoms):\n    n = len(the_array)\n    for i in range(n - 1):\n        j = i + math.floor(randoms[i] * (n - i))\n        the_array[i], the_array[j] = the_array[j], the_array[i]\n    return the_array",
    explanation: "<p>Fisher-Yates: at index i, swap with a uniform random index in [i, n). The injected &#x27;random&#x27; floats make it deterministic for grading. O(n) time, O(1) space, unbiased.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>shuffle(...)</code> directly, so keep it unchanged.</p>",
  },
  "cafe-order-checker": {
    code: "# Merge-check with three indices: each served order must be the next\n# pending item of register 1 or register 2, in sequence.\n# O(n) time, O(1) space.\ndef isFirstComeFirstServed(take_out, dine_in, served):\n    t = d = 0\n    for order in served:\n        if t < len(take_out) and order == take_out[t]:\n            t += 1\n        elif d < len(dine_in) and order == dine_in[d]:\n            d += 1\n        else:\n            return False\n    return t == len(take_out) and d == len(dine_in)",
    explanation: "<p>Merge-check with three indices: each served order must be the next pending item of register 1 or register 2, in sequence. O(n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>isFirstComeFirstServed(...)</code> directly, so keep it unchanged.</p>",
  },
  "simulate-5-from-7": {
    code: "# Rejection sampling: roll rand7 (fed from the injected rolls),\n# throw away 6 and 7, keep 1-5. Uniform because the kept outcomes are equally likely.\ndef rand5(rolls):\n    for roll in rolls:\n        if roll <= 5:\n            return roll\n    raise ValueError('Ran out of rolls')",
    explanation: "<p>Rejection sampling: roll rand7 (fed from the injected rolls), throw away 6 and 7, keep 1-5. Uniform because the kept outcomes are equally likely.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>rand5(...)</code> directly, so keep it unchanged.</p>",
  },
  "simulate-7-from-5": {
    code: "# Two rand5 rolls form a uniform 1..25 grid; keep only the first 21 cells\n# (21 = 3 * 7) and mod into 1..7. Reject 22-25 to stay uniform.\ndef rand7(rolls):\n    i = 0\n    while i + 1 < len(rolls) + 1:\n        a, b = rolls[i], rolls[i + 1]\n        i += 2\n        value = (a - 1) * 5 + b\n        if value <= 21:\n            return ((value - 1) % 7) + 1\n    raise ValueError('Ran out of rolls')",
    explanation: "<p>Two rand5 rolls form a uniform 1..25 grid; keep only the first 21 cells (21 = 3 * 7) and mod into 1..7. Reject 22-25 to stay uniform.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>rand7(...)</code> directly, so keep it unchanged.</p>",
  },
  "two-egg-problem": {
    code: "# Decreasing-interval strategy: first drops at n, n+(n-1), n+(n-2)...\n# so worst case is always n drops. Answer: smallest n with n(n+1)/2 >= floors.\ndef twoEggDrops(n):\n    drops = 0\n    covered = 0\n    while covered < n:\n        drops += 1\n        covered += drops\n    return drops",
    explanation: "<p>Decreasing-interval strategy: first drops at n, n+(n-1), n+(n-2)... so worst case is always n drops. Answer: smallest n with n(n+1)/2 &gt;= floors.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>twoEggDrops(...)</code> directly, so keep it unchanged.</p>",
  },
  "find-repeat-space-edition": {
    code: "# O(1)-space via binary search on the VALUE range 1..n: count how many\n# numbers fall in the lower half; the half with too many holds a repeat.\n# O(n log n) time, O(1) space - never modifies the input.\ndef findRepeatSpaceEdition(numbers):\n    floor, ceiling = 1, len(numbers) - 1\n    while floor < ceiling:\n        midpoint = floor + (ceiling - floor) // 2\n        count = sum(1 for x in numbers if floor <= x <= midpoint)\n        if count > midpoint - floor + 1:\n            ceiling = midpoint\n        else:\n            floor = midpoint + 1\n    return floor",
    explanation: "<p>O(1)-space via binary search on the VALUE range 1..n: count how many numbers fall in the lower half; the half with too many holds a repeat. O(n log n) time, O(1) space - never modifies the input.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findRepeatSpaceEdition(...)</code> directly, so keep it unchanged.</p>",
  },
  "find-repeat-beast-mode": {
    code: "# Beast mode: treat values as linked-list pointers; a duplicate value\n# means two nodes point at the same node, i.e. a cycle entry. Walk n steps\n# to enter the cycle, measure cycle length, then offset two pointers.\n# O(n) time, O(1) space.\ndef findRepeatBeastMode(numbers):\n    slow = fast = numbers[0]\n    while True:\n        slow = numbers[slow]\n        fast = numbers[numbers[fast]]\n        if slow == fast:\n            break\n    slow = numbers[0]\n    while slow != fast:\n        slow = numbers[slow]\n        fast = numbers[fast]\n    return slow",
    explanation: "<p>Beast mode: treat values as linked-list pointers; a duplicate value means two nodes point at the same node, i.e. a cycle entry. Walk n steps to enter the cycle, measure cycle length, then offset two pointers. O(n) time, O(1) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findRepeatBeastMode(...)</code> directly, so keep it unchanged.</p>",
  },
  "find-duplicate-files": {
    code: "# Group by contents (real version would hash the first chunk), then emit\n# groups of 2+ paths ordered oldest-edit-first - the original comes first,\n# later copies are the suspects. O(n) time over the file list.\ndef findDuplicateFiles(files):\n    seen, dupes = {}, []\n    for f in files:\n        prior = seen.get(f['contents'])\n        if prior is None:\n            seen[f['contents']] = f\n        elif f['lastEditedAt'] >= prior['lastEditedAt']:\n            dupes.append([prior['path'], f['path']])\n        else:\n            dupes.append([f['path'], prior['path']])\n            seen[f['contents']] = f\n    return sorted(dupes, key=lambda p: p[1])",
    explanation: "<p>Group by contents (real version would hash the first chunk), then emit groups of 2+ paths ordered oldest-edit-first - the original comes first, later copies are the suspects. O(n) time over the file list.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>findDuplicateFiles(...)</code> directly, so keep it unchanged.</p>",
  },
  "merge-sorted-arrays": {
    code: "# Standard two-pointer merge: repeatedly take the smaller head.\n# O(n + m) time - never concatenate-and-sort (that's O((n+m) log(n+m))).\ndef mergeArrays(mine, alices):\n    merged, i, j = [], 0, 0\n    while len(merged) < len(mine) + len(alices):\n        if i < len(mine) and (j >= len(alices) or mine[i] < alices[j]):\n            merged.append(mine[i]); i += 1\n        else:\n            merged.append(alices[j]); j += 1\n    return merged",
    explanation: "<p>Standard two-pointer merge: repeatedly take the smaller head. O(n + m) time - never concatenate-and-sort (that&#x27;s O((n+m) log(n+m))).</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>mergeArrays(...)</code> directly, so keep it unchanged.</p>",
  },
  "url-shortener": {
    code: "# Bijection both ways: url->id and id->url dicts. Re-shortening the same\n# URL returns the existing id; restore is a dict lookup. O(1) per op.\ndef runShortener(ops):\n    code_to_url, url_to_code, results = {}, {}, []\n    next_id = 0\n\n    def to36(n):\n        digits = '0123456789abcdefghijklmnopqrstuvwxyz'\n        if n == 0:\n            return '0'\n        out = ''\n        while n:\n            out = digits[n % 36] + out\n            n //= 36\n        return out\n\n    for op in ops:\n        if op[0] == 'shorten':\n            url = op[1]\n            if url in url_to_code:\n                results.append(url_to_code[url])\n            else:\n                code = to36(next_id)\n                next_id += 1\n                url_to_code[url] = code\n                code_to_url[code] = url\n                results.append(code)\n        else:\n            results.append(code_to_url.get(op[1]))\n    return results",
    explanation: "<p>Bijection both ways: url-&gt;id and id-&gt;url dicts. Re-shortening the same URL returns the existing id; restore is a dict lookup. O(1) per op.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>runShortener(...)</code> directly, so keep it unchanged.</p>",
  },
  "graph-coloring": {
    code: "# Greedy coloring: for each node, take the first color no neighbor uses.\n# Legal with D+1 colors for max degree D. Loops (self-edges) are impossible\n# to color - raise. O(N + M) time.\ndef colorGraph(graph, colors):\n    node_to_color = {}\n    for label, neighbors in graph.items():\n        if label in neighbors:\n            raise ValueError(f'Legal coloring impossible for node with loop: {label}')\n        illegal = {node_to_color[n] for n in neighbors if n in node_to_color}\n        for color in colors:\n            if color not in illegal:\n                node_to_color[label] = color\n                break\n        else:\n            raise ValueError('Ran out of colors')\n    return node_to_color",
    explanation: "<p>Greedy coloring: for each node, take the first color no neighbor uses. Legal with D+1 colors for max degree D. Loops (self-edges) are impossible to color - raise. O(N + M) time.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>colorGraph(...)</code> directly, so keep it unchanged.</p>",
  },
  "mesh-message": {
    code: "# Breadth-first search from the sender, recording how we reached each node,\n# then backtrack from the recipient to rebuild the shortest path.\n# O(N + M) time, O(N) space.\nfrom collections import deque\n\ndef getPath(graph, start_node, end_node):\n    if start_node not in graph or end_node not in graph:\n        raise ValueError('Node not in graph')\n    queue = deque([start_node])\n    previous = {start_node: None}\n    while queue:\n        current = queue.popleft()\n        if current == end_node:\n            path, n = [], end_node\n            while n is not None:\n                path.append(n)\n                n = previous[n]\n            return path[::-1]\n        for neighbor in graph[current]:\n            if neighbor not in previous:\n                previous[neighbor] = current\n                queue.append(neighbor)\n    return None",
    explanation: "<p>Breadth-first search from the sender, recording how we reached each node, then backtrack from the recipient to rebuild the shortest path. O(N + M) time, O(N) space.</p><p>Same function name as the JavaScript version &mdash; the grader calls <code>getPath(...)</code> directly, so keep it unchanged.</p>",
  },
};
